### ISSUE TITLE
Write final paper/presentation due 12/7

### ISSUE THREAD

**Issue by joseph-zhong** [joseph-zhong/LipReading#8]

**Comment by supernaiter** [comment]
Hi, I'm really impressed with this well-constructed project!
Now I'm curious what papers or models did you refer to? Thanks!

**Comment by rfrowe** [comment]
Here's the [paper](https://github.com/joseph-zhong/LipReading/files/4309557/CSE546_Project__Lip_Reading_Project_Proposal.pdf) which includes our cited works. You can find everything else in 
 our README
